### ISSUE TITLE
feat: improve tracking events

### ISSUE THREAD

**Issue by sahithyandev** [Vigilance-DAO/VigilanceDAO#49]
- [x] Add /event server endpoint
- [x] Create a new id for user on install
- [x] Send events to  /event
